server:
  port: 8184
  servlet:
    context-path: /elastic-query-web-client

spring:
  application:
    name: elastic-query-web-client
  profiles:
    active: elastic_query_web
  config:
    import: 'optional:configserver:http://localhost:8888'
  cloud:
    config:
      name: elastic-query-web-client,config-client
      uri: http://localhost:8888
      username: spring_cloud_user
#      password: springCloud_Pwd!
      password: '{cipher}7a0d735158a760bab4ffb791ca55f52df9aa3a2b27b8411e968264d7726cc7597ea9ff5a57dae90fd68c9c09ba6a6970'
      allow-override: true
    loadbalancer:
      ribbon:
        enabled: false
  thymeleaf:
    cache: false

encrypt:
  key: APODNU3093r2rbjzxcn09u213asdhy08WRFH

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/euraka/
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2

#----------------------------------------------------------------------------------------------------------------------
# Uncomment below config properties to build locally. Otherwise, start local config server before building the project.
#----------------------------------------------------------------------------------------------------------------------
#elastic-query-web-client:
#  webclient:
#    connect-timeout-ms: 10000
#    read-timeout-ms: 10000
#    write-timeout-ms: 10000
#    max-in-memory-size: 10485760 # 10MB
#    base-url: 'http://elastic-query-service/elastic-query-service/documents'
#    service-id: elastic-query-service
#    instances:
#      - id: elastic-query-service-1
#        host: localhost
#        port: 8183
#      - id: elastic-query-service-2
#        host: localhost
#        port: 8183
#  query-by-text:
#    method: POST
#    uri: '/get-document-by-text'
#  query-by-text-with-analytics:
#    method: POST
#    uri: '/get-document-by-text-with-analytics'