retry-config:
  initial-interval-ms: 1000
  max-interval-ms: 10000
  multiplier: 2.0
  maxAttempts: 3
  sleep-time-ms: 2000

elastic-query-web-client:
  webclient:
    connect-timeout-ms: 10000
    read-timeout-ms: 10000
    write-timeout-ms: 10000
    max-in-memory-size: 10485760 # 10MB
    base-url: 'http://elastic-query-service/elastic-query-service/documents'
    service-id: elastic-query-service
    instances:
      - id: elastic-query-service-1
        host: localhost
        port: 8183
      - id: elastic-query-service-2
        host: localhost
        port: 8183
  query-by-text:
    method: POST
    uri: '/get-document-by-text'
  query-by-text-with-analytics:
    method: POST
    uri: '/get-document-by-text-with-analytics'