gateway-service:
  timeout-ms: 3000
  failure-rate-threshold: 50
  slow-call-rate-threshold: 50
  slow-call-duration-threshold: 50
  permitted-num-of-calls-in-half-open-state: 10
  sliding-window-size: 10
  min-number-of-calls: 10
  wait-duration-in-open-state: 60000