server:
  port: 8183
  servlet:
    context-path: /elastic-query-service

elastic-query-service:
  version: v1

elastic-query-config:
  text-field: text
  is-repository: true

elastic-config:
  index-name: twitter-index
  connection-url: http://localhost:9200
  connect-timeout-ms: 5000
  socket-timeout-ms: 30000