retry-config:
  initial-interval-ms: 1000
  max-interval-ms: 10000
  multiplier: 2.0
  maxAttempts: 3
  sleep-time-ms: 2000

elastic-config:
  index-name: twitter-index
  connection-url: http://localhost:9200
  connect-timeout-ms: 5000
  socket-timeout-ms: 30000
  is-repository: false

elastic-query-config:
  text-field: text
  is-repository: true

elastic-query-service:
  version: v1
  webclient:
    connect-timeout-ms: 10000
    read-timeout-ms: 10000
    write-timeout-ms: 10000
    max-in-memory-size: 10485760 # 10MB
#    query-type: 'ANALYTICS_DATABASE'
    query-type: 'KAFKA_STATE_STORE'
  query-from-kafka-state-store:
    method: GET
    uri: "http://kafka-streams-service/kafka-streams-service/get-word-count-by-word/{word}"
#    uri: "http://localhost:8187/kafka-streams-service/get-word-count-by-word/{word}"
  query-from-analytics-database:
    method: GET
    uri: "http://twitter-analytics-service/twitter-analytics-service/get-word-count-by-word/{word}"
#    uri: "http://localhost:8188/twitter-analytics-service/get-word-count-by-word/{word}"