retry-config:
  initial-interval-ms: 1000
  max-interval-ms: 10000
  multiplier: 2.0
  maxAttempts: 3
  sleep-time-ms: 2000

kafka-config:
  bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
  schema-registry-url-key: schema.registry.url
  schema-registry-url: http://localhost:8081
  topic-names-to-create:
    - twitter-topic
    - twitter-analytics-topic

kafka-streams-config:
  application-id: kafka-streams-application
  input-topic-name: twitter-topic
  output-topic-name: twitter-analytics-topic
  state-file-location: ${HOME}/kafka-streaming-state
  word-count-store-name: word-count-store

kafka-streams-service:
  version: v1
  custom-audience: kafka-streams-service