services:
  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-latest}
    hostname: elastic-search
    container_name: elastic-search
    ports:
      - '9200:9200'
    environment:
      - node.name=elastic-search
      - discovery.type=single-node
      - cluster.name=es-twitter-cluster
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - 'xpack.security.enabled=false'
    mem_limit: ${ES_MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data:/usr/share/elasticsearch/data
    networks:
      - ${GLOBAL_NETWORK:-elastic}

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    ports:
      - '5601:5601'
    depends_on:
      - elastic-search
    environment:
      ELASTICSEARCH_HOSTS: http://host.docker.internal:9200
    networks:
      - ${GLOBAL_NETWORK:-elastic}

  logstash:
    image: docker.elastic.co/logstash/logstash:${ELASTIC_VERSION}
    command: logstash -f /etc/logstash/conf.d/logback.conf
    ports:
      - '9600:9600'
    depends_on:
      - elastic-search
    volumes:
      - ./config/logback.conf:/etc/logstash/conf.d/logback.conf
      - ./docker-logs/logstash:/logs
    environment:
      LS_JAVA_OPTS: "-Xms256m -Xmx512m"
      CLUSTER_NAME: es-twitter-cluster
      XPACK_MONITORING_ELASTICSEARCH_HOSTS: http://elastic-search:9200
    networks:
      - ${GLOBAL_NETWORK:-elastic}

volumes:
  data:
    driver: local

networks:
  ${GLOBAL_NETWORK}:
