services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-latest}
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - "./data:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=twitter-data-analytics"