services:
  redis:
    image: redis:${REDIS_VERSION:-latest}
    hostname: redis
    command: [ "redis-server", "--appendonly", "yes" ]
    ports:
      - "6379:6379"
    networks:
      - ${GLOBAL_NETWORK:-redis}