spring:
  application:
    name: twitter-to-kafka-service
#  profiles:
#    active: twitter_to_kafka
#  config:
#    import: 'configserver:'
#  cloud:
#    config:
#      name: twitter-to-kafka-service,config-client
#      username: spring_cloud_user
#      password: '1234'
#
#log:
#  app-name: twitter-to-kafka-service
#
twitter-to-kafka-service:
  twitter-keywords:
    - Java
    - Microservices
    - Spring
    - Kafka
    - Elasticsearch
  welcome-message: Hello Spring Microservices!
  enable-mock-tweets: true
  mock-min-tweet-length: 5
  mock-max-tweet-length: 15
  mock-sleep-ms: 5000
