server:
  port: 8761

spring:
  application:
    name: eureka-discovery-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    appname: service-registry-cluster
  server:
    enable-self-preservation: false
    expected-client-renewal-interval-seconds: 20
    eviction-interval-timer-in-ms: 20000
    peer-node-connect-timeout-ms: 20000

logging:
  level:
    ROOT: INFO
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF