server:
  port: 8888

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
#          uri: file://Users/sashankasamantray/my_projects/backend/spring-microservices/twitter-data-streaming/config-server-repository
          uri: https://github.com/ssamparn/config-repo
          default-label: master
          username: ssamparn
          password: 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
          clone-on-start: true
      fail-fast: true
  security:
    user:
      name: spring_cloud_user
      password: springCloud_Pwd!

logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG