server:
  port: 8888

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: file://Users/sashankasamantray/my_projects/backend/spring-microservices/twitter-data-streaming/config-server-repository
#          uri: https://github.com/ssamparn/config-repo
          default-label: master
          username: ssamparn
          password: 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
          clone-on-start: true
      fail-fast: true
  security:
    user:
      name: spring_cloud_user
      password: '{cipher}7a0d735158a760bab4ffb791ca55f52df9aa3a2b27b8411e968264d7726cc7597ea9ff5a57dae90fd68c9c09ba6a6970'
#      password: springCloud_Pwd!
encrypt:
  key: APODNU3093r2rbjzxcn09u213asdhy08WRFH

logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG
